# A Porta do Servidor Java (O Go está na 8080, então o Java fica na 8081)
server.port=8081

# A Conexão com a sua Memória Eterna (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_vault
spring.datasource.username=admin
spring.datasource.password=god_eye_password

# Configurações do Hibernate (A ferramenta que transforma Java em SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Resolve problemas de formatação de data no JSON
